version: '3.8'

services:
  med_db:
    image: postgres:16-alpine
    container_name: med_db
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"  ]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3


volumes:
  database: